Project app: Subject set picker
zooniverse/front-end-monorepo pull request #1731
Opened 2020-07-30 16:30 UTC by eatyourgreens

Add a client-side subject set picker to the workflow selector links, which is shown on click when `workflow.grouped` is set (ie. Panoptes expects you to pass a subject set ID with subject queries for that workflow.)

Package:
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

2020-09-03 21:17 UTC, shaunanoordin approved these changes
## PR Review

Package: `app-project`

This PR adds the "Subject Set Picker" component to the Project page.

- On a Project page with multiple workflows (e.g. `http://localhost:3000/projects/darkeshard/engaging-the-crowds-2020?env=production`), the "click on a workflow to begin the workflow" interaction has changed.
  - Clicking on a workflow - for a workflow that has `workflow.grouped=false` - will result in the user beginning the workflow as expected.
  - Clicking on a workflow - for a workflow that has `workflow.grouped=true` - will instead open the Subject Set Picker modal.
- The Subject Set Picker modal will list all Subject Sets belonging to the workflow ; clicking on a workflow will result in the user beginning the workflow, with the Subject Set selected via URL. (e.g. user will be directed to `http://localhost:3000/projects/darkeshard/engaging-the-crowds-2020/classify/workflow/16106/subject-set/85771`)  
- Subject Set Picker works as a standard modal ; it can be closed by clicking the X close button or pressing the Esc key. Tab navigation works fine (though see UI quirk)

UI quirks:
- (Known) The "close" button on the modal is difficult to see
- (Known) The height of each Subject Card is inconsistent
- (New?) when navigating via keyboard, the highlighted Subject Card has a very hard-to-notice focus style. Like, there's only a small highlighted square in the corner?

<img width="680" alt="Screen Shot 2020-09-03 at 22 16 03" src="https://user-images.githubusercontent.com/13952701/92170690-22a1e700-ee33-11ea-9661-ec20cc87a262.png">

_Believe or not, the "Transformers series" has keyboard focus._

Most of the UI issues however have already been noted on Slack on the `#engaging-crowds` channel, so I'm not too concerned with flagging them.

Tested OK on the Engaging Crowds 2020 project mentioned earlier, on mac OS 10 + Chrome. Subject Set Picker works as expected for grouped workflows, and standard click-to-begin-workflow interaction for un-grouped workflows continue to function fine. 👍 

### Status

LGTM! 👍 

I didn't dig into the tests too deeply though - everything seems to pass, so I'm not sure if your earlier comments (on Slack, I think?) about 'tests being unfinished for this PR' is still accurate.

2020-09-03 21:57 UTC, eatyourgreens commented
Thanks for taking a look @shaunanoordin. Re. Tests: I haven't written any tests for the picker itself, yet. 

The focus behaviour is odd. I see something similar in Firefox.

I've opened #1785 for the close button.

2020-09-04 13:54 UTC, eatyourgreens commented
I haven’t written any stories for the subject set picker either.

2020-09-07 13:26 UTC, eatyourgreens commented on packages/app-project/src/screens/ProjectHomePage/components/Hero/components/WorkflowSelector/components/SubjectSetPicker/components/SubjectSetCard/SubjectSetCard.js
> +          {set_member_subjects_count} subjects
That's a good idea.

2020-09-09 09:32 UTC, eatyourgreens commented
Here's a screenshot with the Annotate subject sets. Layout still needs a bit of work to match the designs.

![Screenshot of Annotate,showing the subject set picker when there are enough subject sets to overflow the initial box.](https://user-images.githubusercontent.com/59547/92581511-b0446300-f287-11ea-93d1-234fa0854d6f.png)

2020-09-10 18:17 UTC, beckyrother reviewed
"the title bar of the modal vanishes off the top of the viewport when there are two or more rows of subject sets." 

Not sure what is meant here, would you mind posting a screenshot?

2020-09-11 11:31 UTC, eatyourgreens commented
@beckyrother I thought the teal title bar had been cropped in the screenshot that I posted. Now that I look at it again, I'm not so sure. I'll work on a story for the storybook, so that we can check it with dummy content.

2020-09-11 12:19 UTC, eatyourgreens commented
@beckyrother here it is in the storybook. The title styling should be fixed by #1787 

![Screenshot of the light mode subject set picker in the storybook.](https://user-images.githubusercontent.com/59547/92924737-54b5d900-f431-11ea-9af3-5004efb01ea7.png)

2020-09-11 15:20 UTC, beckyrother requested changes
Couple small spacing changes (sorry if some have been addressed by #1786 ): 

![92924737-54b5d900-f431-11ea-9af3-5004efb01ea7](https://user-images.githubusercontent.com/1392130/92943342-460ef800-f418-11ea-94cf-9821b9d72e35.png)

2020-09-14 08:45 UTC, eatyourgreens commented
@beckyrother no problem. I think the spacing around the modal's content should be fixed by #1786. I've overridden the line-height on the heading, and the default margins on paragraphs, to set up the 15px spacing. Here's a screenshot with 30px/15px spacing. One question: how should the content of the grey box respond at small widths? Should the box padding remain at 30px and then the subject set cards be justified to fit?

![Screenshot of the AnnoTate subject sets in a narrow box, so that three subject sets are visible and content overflows to the right.](https://user-images.githubusercontent.com/59547/93063736-98e1ed00-f66e-11ea-92af-f11e1a2b6940.png)

2020-09-14 11:33 UTC, eatyourgreens commented
Here's a 5 column grid on wide screens, 3 column grid on narrow screens.

![Screenshot with 5 subject set cards per row and the picker covering the full width of the window.](https://user-images.githubusercontent.com/59547/93080780-2aa92480-f686-11ea-9284-fe1cc242e310.png)

![Screenshot with 3 subject set cards per row and the picker modal not quite covering the window.](https://user-images.githubusercontent.com/59547/93080818-3399f600-f686-11ea-8aed-1ca4957ef327.png)

2020-09-14 18:46 UTC, beckyrother commented
@eatyourgreens yep! That looks perfect, thank you!

2020-09-15 08:52 UTC, eatyourgreens commented
Now that #1786 has merged, all modals have 20px spacing between the title bar and the content. I'm going to add an extra 10px margin to the top of the content for this one.

2020-09-15 09:08 UTC, eatyourgreens commented
@beckyrother here it is with the changes from #1786. The close button colour and title bar height have been fixed, and I've added extra padding to the content at the top.

![Subject set picker layout on a wide screen, with a purple layout grid overlaid.](https://user-images.githubusercontent.com/59547/93190243-05c2b900-f73b-11ea-92fa-c76795ddfdec.png)

![Subject set picker layout on a narrow screen, with a purple layout grid overlaid.](https://user-images.githubusercontent.com/59547/93190283-11ae7b00-f73b-11ea-8b35-b29443948eb1.png)

2020-09-15 15:22 UTC, beckyrother commented
Looks great, thanks @eatyourgreens !

2020-09-15 15:43 UTC, merged