Project: remove classes for _app and page containers
zooniverse/front-end-monorepo pull request #1971
Opened 2021-01-12 12:00 UTC by eatyourgreens

This replaces `_app.js`, `ProjectHomePageContainer` and `ClassifyPageContainer` with functional components.

This is the first of a series of PRs where I'll be replacing class components with functions in the project app. I'm hoping that this will give us [faster page build times and a smaller memory footprint](https://blog.usejournal.com/react-hooks-the-most-performant-way-to-write-react-393e135e1cc) in Node. It may make the upgrade to Next 10 easier too.

Package:
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

2021-01-28 17:00 UTC, srallen requested changes
One minor request to update how the store is connected per recommended migration path from mobx-react.

2021-01-28 17:05 UTC, eatyourgreens commented on packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js
> +export default inject(storeMapper)(observer(ProjectHomePageContainer))
Unfortunately, the project app can't use context yet. It's on an older version of mobx-react, and the last attempt to upgrade caused problems. https://github.com/zooniverse/front-end-monorepo/issues/1839

2021-01-28 17:11 UTC, eatyourgreens commented
Updated the description because this should also fix the `missing Html component` warnings during builds.

2021-01-28 17:23 UTC, eatyourgreens commented on packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js
> +export default inject(storeMapper)(observer(ProjectHomePageContainer))
That said, I will open a PR to upgrade mobx and mobx-react across the board.

2021-01-28 17:38 UTC, eatyourgreens commented on packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js
> +export default inject(storeMapper)(observer(ProjectHomePageContainer))
OK. #2009, if it doesn't break classifications, will let us use in the project app.

2021-02-01 11:59 UTC, eatyourgreens commented on packages/app-project/src/screens/ProjectHomePage/ProjectHomePageContainer.js
> +export default inject(storeMapper)(observer(ProjectHomePageContainer))
#2009 is ready for review now. Once that's merged, I'll be able to remove `inject` here.

2021-02-01 23:14 UTC, eatyourgreens commented
I’ll update this tomorrow to remove `inject` from the page containers.

2021-02-02 10:20 UTC, eatyourgreens commented
@srallen this should be ready for review again.

2021-02-02 11:57 UTC, eatyourgreens commented
I'm seeing the deployed commit being logged (and `store.user.checkCurrent()` being run) on every client-side page transition. I'll push a fix for that.

2021-02-02 12:14 UTC, eatyourgreens commented
I'm also seeing `Store.create(snapshot)` run on every client-side transition, which is unexpected. On master, `Store.create(snapshot)` only runs once, when the page first loads in the browser.

2021-02-02 15:00 UTC, eatyourgreens commented
Our app component code is taken from [a very old example of NextJS with MST](https://github.com/vercel/next.js/blob/af9214b302c42df141647bf5a01feb5ab0124206/examples/with-mobx-state-tree/pages/_app.js). The latest example has been updated to use functional components and hooks.
https://github.com/vercel/next.js/blob/5201cdbaeaa72b54badc8f929ddc73c09f414dc4/examples/with-mobx-state-tree/pages/_app.js#L4-L12

2021-02-02 16:16 UTC, eatyourgreens commented
I've adapted the `useStore` hook from the MST example for our code. Hopefully, that will stop the store from being recreated every time the `MyApp` component renders.

2021-02-02 16:30 UTC, eatyourgreens commented
With the lates commits, I'm seeing `initStore()` run on each page transition, but only seeing `Store.create(snapshot)` run when the page first loads. I think that's the behaviour that we want.

2021-02-03 09:39 UTC, eatyourgreens commented
The [NextJS MST example](https://github.com/vercel/next.js/tree/master/examples/with-mobx-state-tree) gets the store state, as the `initialState` prop, on each page render and applies it with `applySnapshot`. Naively using that with our code, the initial snapshot overwrites the logged-in user (and any other local changes) on each page render. So, you go to the home page, you log in, you go to Classify and the classifier hangs because there's no logged-in user any more.

I've worked around this by only applying the `project` and `ui` snapshots from the server. I'm not sure that's the best solution, but it works. I'm open to suggestions on how to improve this.

2021-02-04 09:09 UTC, eatyourgreens commented on packages/app-project/pages/_document.js
> +      <Html lang="en">
At some point, this will need to be set dynamically. Maybe wait until after the Next 10 upgrade for that?

2021-02-04 19:52 UTC, srallen approved these changes
One non-blocking comment I have is to consider renaming `ProjectHomePageContainer` to `ProjectHomePageConnector` since all it is doing is connecting to the store and getting data. The convention I've started to use is `Connector` component is for store connections, `Container` component is for local react state, and then the named component for the view. This way we have separation between local react state and store connections and can tested separately as well, or easily swap out the store for something else if we need to in the future and can id quickly which components are just store connections.

2021-02-04 19:52 UTC, srallen commented on packages/app-project/stores/initStore.js
> +    const initialState = snapshot ?? {}
I forgot that this operator is in stage 4. Nice.

2021-02-04 19:52 UTC, srallen commented on packages/app-project/stores/initStore.js
> +      Oon't overwrite the stored user, collections, recents or stats in the browser.
```suggestion
      Don't overwrite the stored user, collections, recents or stats in the browser.
```

2021-02-04 22:09 UTC, merged