WIP: Use links for workflow and subject set selection
zooniverse/front-end-monorepo pull request #2335
Opened 2021-08-03 18:57 UTC by eatyourgreens

Remove local state from the workflow menu so that workflow buttons are pure links. Convert the subject set picker to use pure links too. Update server-side data fetching so that subject sets are only fetched when you load a grouped workflow.

Package:
app-project

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

2021-08-04 09:06 UTC, eatyourgreens commented on packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.spec.js
>    }
This isn't used any more in these tests, but the `UserPersonalization` tests fail if I delete it.

2021-08-04 09:08 UTC, eatyourgreens commented on packages/app-project/src/helpers/getStaticPageProps/getStaticPageProps.spec.js
>    }
This isn't used any more in these tests, but the `UserPersonalization` tests fail if I delete it.

2021-08-04 13:06 UTC, eatyourgreens commented
This needs some tidying up but should be working now. I think I've remembered to update the storybook too (fingers crossed.)

2021-08-04 15:43 UTC, srallen reviewed
I don't know if this is within the scope of this PR or not, but the `workflowFromURL` needs to be checked if it's a workflow that the user has permission to load before we attempt anything else. I have been working on a local branch that redirects the user back to workflow selection if the user doesn't have access to it yet in the context of the workflow assignment feature, however, this could apply in other cases too I think. What happens if someone types in a URL with a workflow id that doesn't belong to the project?

The workflow assignment case is more complicated because it depends on knowing if we have a user and if the user project preferences have loaded, which is all done client side. I think I'll have to abandon my WIP branch based off the changes I see here, but depending on the reason, it may be possible to do a redirect server side.

2021-08-04 16:57 UTC, eatyourgreens commented
> What happens if someone types in a URL with a workflow id that doesn't belong to the project?

I think that’s a 404, if the ID isn’t an active workflow for the project eg. https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11236

2021-08-04 18:27 UTC, srallen commented
> I think that’s a 404, if the ID isn’t an active workflow for the project eg. https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11236

Unfortunately long term we can't do it this way, since admins, project owners and collaborators should have permission to load inactive workflows that do belong to the project. If the workflow doesn't belong to the project, perhaps we can rely on this.

2021-08-04 22:29 UTC, eatyourgreens commented
Outside the scope of this PR, but NextJS has Preview Mode, which might be useful for previewing private workflows or projects. 
https://nextjs.org/docs/advanced-features/preview-mode

2021-08-05 13:02 UTC, eatyourgreens commented
The `Hero` and `WorkflowMenuModal` stories are broken, so the changes here can't be checked in the storybook at the moment. I've fixed those in #2337.

2021-08-13 16:15 UTC, srallen requested changes
I have some minor syntax suggestions. I'd like the change to the test running to be removed and proposed separately. Otherwise, the refactor looks good.

2021-08-13 16:19 UTC, eatyourgreens commented on packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
> +  ...rest }
This is needed for the storybook to list the default props in the component Docs page. It can't read them if they're destructured separately.

2021-08-13 16:20 UTC, eatyourgreens commented on packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
> +  ...rest }
Having said that, I don't think we have stories at this level.

2021-08-13 16:21 UTC, eatyourgreens commented on packages/app-project/package.json
> +    "test:ci": "BABEL_ENV=test mocha --exit --config test/.mocharc.json --reporter=min \"./{src,pages,stores}/**/*.spec.js\""
Sure. I think I was seeing tests that never exited, but I don't think that's a problem here.

2021-08-13 16:59 UTC, eatyourgreens commented on packages/app-project/package.json
> +    "test:ci": "BABEL_ENV=test mocha --exit --config test/.mocharc.json --reporter=min \"./{src,pages,stores}/**/*.spec.js\""
This is gone now.

2021-08-16 14:43 UTC, srallen commented on packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
> +  ...rest }
Indeed there aren't any for this component, so an unnecessary change.

2021-08-16 14:55 UTC, srallen approved these changes

2021-08-16 15:00 UTC, merged

2021-08-17 06:35 UTC, eatyourgreens commented on packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
> +  ...rest }
Not really. I’ve changed the component props here, and destructured function arguments are the recommended syntax for default props going forward. 
https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components

2021-08-17 14:39 UTC, srallen commented on packages/app-project/src/shared/components/WorkflowSelector/components/WorkflowSelectButton/WorkflowSelectButton.js
> +  ...rest }
I have no idea what point you're trying to make here is. I never said we should revert back to using `defaultProps` and not destructure them.