Classifier: add 'Literal Insertion' text tags
zooniverse/front-end-monorepo pull request #2384
Opened 2021-08-23 20:46 UTC by shaunanoordin

## PR Overview

Package: `lib-classifier`
Closes #2331 

We have a special request for the [Davy Notebooks project](https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/) on FEM. Users want to have the `&` text modification tag, but they want it to _behave differently._ Instead of the standard tag insertion that goes `[&]...[/&]`, the insertion is literally just `&`. _I know, I know._

- ⚠️ This PR is a quick fix to address the feature request and should be treated as a short term measure.
  - A proper long-term solution is to split the "text modification tags" into a few categories: standard `[tag]...[/tag]`, single `[tag]`, and literal/raw `tag`
  - A long term solution also needs to visually distinguish the various categories of tag insertions, as _different UI elements should indicate different interaction behaviour._
- This PR adds an array of "special exceptions" to text tags, which will be treated as **literal insertion text tags.** (Actually, tell me if you can think of a better term.)
  - If a user attempts to use a "literal insertion" text tag, the standard `TextTask.setTagSelection()` will be overridden by `TextTask.setTagSelection_literalInsertion()`
  - As of now, only the `&` tag is a _hardcoded global exception._

### Testing

- Use a Text Transcription project that's configured to have the `&` text tag modifier, e.g. https://local.zooniverse.org:8080/?env=staging&project=1929&workflow=3459
- Transcribe a line. Type some text. Click on the `&` button to insert the `&` symbol. (Yes, the same thing that happens when you press Shift-7 on a US keyboard.)
- Baseline check: every other text tag should behave normally, with start `[tag]`s and end `[/tag]`s!

_Step 1a: either set the cursor to where you want to insert the `&` symbol, OR..._

<img width="577" alt="Screenshot 2021-08-23 at 21 26 57" src="https://user-images.githubusercontent.com/13952701/130516680-7df5d2fc-dfcb-4dd7-a3e1-101139d6bba2.png">

_Step 1b: highlight the text you want to REPLACE with the `&` symbol..._

<img width="577" alt="Screenshot 2021-08-23 at 21 27 14" src="https://user-images.githubusercontent.com/13952701/130516693-fd2e3388-3840-4845-800c-900e56bebb79.png">

_Step 2: and click the `&` button. Done!_

<img width="579" alt="Screenshot 2021-08-23 at 21 27 26" src="https://user-images.githubusercontent.com/13952701/130516713-59a37855-61b0-4b89-bb5f-84ce9ba93597.png">

### Status

Ready for review. Tagging @snblickhan for comments [&][/&] feedback.

2021-08-24 08:16 UTC, eatyourgreens requested changes
Changes look good to me, but I'd also ask for `&` to be added to the task story, and for the this new function to be added to the text tagging tests in the spec file.

2021-08-24 08:16 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/TextTask/components/TextTask/TextTask.js
> +    const endTag = `[/${textTag}]`
I don't see these used anywhere, so I think you can get rid of them?

2021-08-24 17:25 UTC, shaunanoordin commented
Thanks for the review, @eatyourgreens ! Feedback has been addressed:

## PR Update

- Tests now include _TextTask (component) > text tagging (special case for literal insertions)_
  - I did _not_ update TextTask.spec.js from enzyme to react-testing-library, however. I tried to, but only got halfway before my event tests started breaking, so this has to be a separate thing.
- TextTask's Storybook Story now has the `&` text tag.
- Code cleaned up, notably removing those unused startTag/endTag in the literalInsertion code.

2021-08-25 13:22 UTC, eatyourgreens approved these changes

2021-08-25 13:22 UTC, eatyourgreens commented
:shipit:

2021-08-31 14:14 UTC, snblickhan approved these changes
Looks good to me!

2021-08-31 15:00 UTC, merged