Add survey task feedback
zooniverse/front-end-monorepo pull request #2403
Opened 2021-09-02 22:15 UTC by mcbouslog

Package:
- lib-classifier

Describe your changes:
- as per ADR 33 adds feedback for survey task

Questions
- what should the strategy name be? currently I used "Survey", but if we know there'll be more complex versions (comparing choice answers) then maybe it should be something like "Survey Simple"/`surveySimple`?
- open to any variable renaming, particularly in the reducer

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

2021-09-07 15:12 UTC, srallen requested changes
I have a few minor syntax suggestions, but otherwise this is looking great. I'm submitted this as requesting changes because I do think we should name the strategy both in code and in the docs as "Survey: Simple" or `surveySimple` just in case we do get asked to setup a strategy in the future that evaluates the choice questions as well. 

I ran through the test project's subjects and submitted a variety of success and failure annotations and each evaluated as expected. Thanks for setting this up!

2021-09-07 15:12 UTC, srallen commented on packages/lib-classifier/src/store/feedback/strategies/survey/index.spec.js
> +    expect(index.labComponent).to.equal(null)
Non-blocking. This can use `null()` 
```suggestion
    expect(index.labComponent).to.be.null()
```

2021-09-07 15:12 UTC, srallen commented on packages/lib-classifier/src/store/feedback/strategies/survey/index.spec.js
> +    expect(index.validations).to.equal(null)
```suggestion
    expect(index.validations).to.be.null()
```

2021-09-07 15:12 UTC, srallen commented on packages/lib-classifier/src/store/feedback/strategies/survey/reducer.js
> +  const chosenIds = choices.map(choice => choice.choice)
Maybe just a bit of clarity here:
```suggestion
  const chosenIds = choices.map(choiceObject => choiceObject.choice)
```

2021-09-13 14:47 UTC, srallen approved these changes
LGTM. Thanks!

2021-09-14 14:15 UTC, merged

2021-09-15 21:21 UTC, mcbouslog commented
Closes #1305