Drawing tools: edit freehand lines
zooniverse/front-end-monorepo pull request #3446
Opened 2022-07-19 08:55 UTC by eatyourgreens

- Add an `editing` state to freehand lines.
- Double-click to start editing, then click a second time to select the area to cut.
- Drag the open drag handle to draw. Editing automatically ends when you reach the target point.
- Closed shapes aren't fully supported at the moment.
- Undo isn't supported at the moment, to cancel accidental cutting of line segments.

## Package
lib-classifier

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
- What user actions should my reviewer step through to review this PR?
- Which storybook stories should be reviewed?
- Are there plans for follow up PR’s to further fix this bug or develop this feature?

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [ ] The PR creator has listed user actions to use when testing the new feature
- [ ] Unit tests are included for the new feature
- [ ] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

2022-07-19 12:48 UTC, eatyourgreens commented
Now with support for clipping a closed loop.

https://user-images.githubusercontent.com/59547/179753840-bd7cb9ad-fb34-46a9-8913-a1c34c20800c.mov

2022-07-19 15:00 UTC, eatyourgreens commented
Added guide lines to show the path that's been cut.


https://user-images.githubusercontent.com/59547/179782605-619a9d9a-c8f8-4487-a5c4-0f1d44d13164.mov

2022-07-22 10:06 UTC, eatyourgreens commented
The interaction design here is very unforgiving of errors. I think it would be easier to use if the interactions went something like this:
1. Click (or double-click) and drag to place and move the start point.
2. Click and drag to place the end point.
3. Click (or double-click) the selected line segment in order to remove it.

Ideally, all these actions should be undoable (preferably with a gesture on tablets and touchscreens.)

If I start editing by mistake, how should I cancel? 'Esc' might work, but isn't available when drawing on a tablet with a stylus.

2022-08-15 13:46 UTC, shaunanoordin commented
I'm making a point to review this whole PR by the end of today, since I've unfortunately been ignoring it for the past 2 weeks+ . Bootstrapping, and go!

2022-08-15 18:39 UTC, shaunanoordin requested changes
## PR Review

Package: `lib-classifier`
Part of: "Correct-A-Cell" project

This PR modifies the (experimental) **Freehand Drawing Line** tool, allowing users to edit _a selected segment_ of the freehand line (FHL).

- Original intent of the tool is this: if Caesar/any ML service provides a predefined freehand line shape, then allow the user to "correct" that line shape to better match the Subject image (usually the membrane of a biological cell).
- New behaviour: user can edit segments of the FHL mark (aka "correction feature")
  - user indicates the start of the segment by _double clicking_ on an existing FHL mark (closed or otherwise), then clicking at the end of the segment.
  - user can then use the "continue drawing" feature/behaviour of the FHL to correct the segment

This PR adds a significant new feature, which functions under _certain conditions,_ but there are two major issues.
- ❗ [blocking] the correction feature does not work on **Chrome 104.**
- ⚠️ [not-blocking] the correction feature acts very strangely if it's interrupted in the middle of the correction process (e.g. user accidentally clicking elsewhere to create a new line, or changing tools)

More details in dev notes. (EDIT: I was so focused on testing that I forgot to do a code read - I'll do that on the next pass.)

### Dev Notes

Full details of new behaviour:

1. (initial) let's say a user creates a new FHL mark. (The screenshots below use closed shapes, but open shapes/unclosed lines work similarly.)
     <img width="200" alt="Screenshot 2022-08-15 at 18 40 40" src="https://user-images.githubusercontent.com/13952701/184689943-834d8ade-e900-4140-88a7-67d4bdffe3fc.png">
2. (editing) user **double-clicks** on a part of the FHL to place the _"START of the segment to be replaced"._ The FHL is now in editing mode.
    <img width="200" alt="Screenshot 2022-08-15 at 18 40 52" src="https://user-images.githubusercontent.com/13952701/184690035-e29a9f93-e0f3-4fa5-aae7-3f3d269f69e8.png">
3. (editing) user **clicks** on another part of the FHL to place the _"END of the segment to be replaced"_ 
    <img width="200" alt="Screenshot 2022-08-15 at 18 41 00" src="https://user-images.githubusercontent.com/13952701/184690063-386dd864-6983-423b-8bd0-a92ad44cb4fe.png">
4. (editing) user can now **drag** the "start" marker to the "end" marker. The dragging (drawing) process _draws a new line segment..._ 
5. (completion) ...and when the user reaches the "end" marker, the "correction" process is complete, and the new line segment replaces the previously marked one.  
    <img width="200" alt="Screenshot 2022-08-15 at 18 41 13" src="https://user-images.githubusercontent.com/13952701/184690103-d3202329-1241-4d4e-8855-da215fdaf1fa.png">

With this in mind, let's examine the issues mentioned earlier.

**Issue 1:** the correction feature does not work on Chrome.

Details:
- Tested on macOS + Chrome 104, standard desktop mode, with a mouse.
- Double clicking on a FHL mark doesn't do anything.
- In fact, replacing the path.onClick handler on `FreehandLine.js` with a simple console.log indicates that _no click events_ are triggering

Analysis:
- The problem lies with `draggable.js`'s `dragStart()`, which runs `setPointerCapture()`
- This only affects Chrome. Firefox and Safari aren't affected.
- I _think_ that when a user **clicks** on the FHL path...
  - user's mouse goes down, and path's "pointer down" triggers (if it had any).
  - event bubbles up to draggable, whose "pointer down" starts the pointer capture.
  - user's mouse goes up, and path's "pointer up" triggers (if it had any) then its "on click" triggers.
    - however, on Chrome, the pointer event is captured, so the "on click" handler gets ignored.
  - event bubbles up to draggable, whose "pointer up" stops the pointer capture.

Solutions?:
- add onPointerDown and onPointerUp to the FHL's `path`, which capture the pointer events _before_ the parent's `draggable` does the same?  
- After all, when there's a draggable child inside a draggable parent, the child's click/drag/pointer events all trigger properly, so I assume that's because the child captured the pointer before the parent could.

⚠️ Even if we have a solution, the fundamental discrepancy between Chrome and Firefox/Safari's behaviours is making me a bit wary. I might need to run this test again on BrowserStack to confirm it's not just an issue specific to my machine. (And if it isn't, what else is borked?)

**Issue 2:** the correction feature acts very strangely if interrupted.

Details:
- The correction feature works perfectly if the user follows steps 1 to 5 (see notes above) of the new behaviour.
- If the users encounters an interruption during steps 2 to 4 (the "editing" stage), the mark becomes "unstable"
- An interruption is any of the following:
  - User clicks on the canvas, triggering the "draw new FHL" action (very easy to accidentally do)
  - User changes the active Drawing Tool
  - User selects another existing mark
- "Unstable" can mean any of the following:
  - FHL mark stays in editing mode, even though this isn't a valid state to finish on
  - FHL starts "shrinking" due to confusion over what's the "current" selected segment
  - FHL is broken into multiple segments (difficult to replicate)
- **(special case)** If a user has already placed the Start and End marks for the segment, and then _proceeds to click on the FHL mark again,_ the FHL mark gets very confused as to which bits are selected, especially if you _alternately_ click on the sections before the Start/after the End mark.

Solutions?:
- Mark should listen for possible interruption scenarios (e.g. mark losing focus) and trigger a "cancel" process.
- (space left blank for future ideas) (still thinking about the special case)

### Status

I think the "doesn't work in Chrome" issue is a major one that needs to be addressed before this PR can be approved. ❗ This is required for baseline functionality.

The "correction feature acts strangely if interrupted" issue, while also significant, is something that can be handled in a separate PR. 👌 I'm aware that 1. this is an experimental tool anyhoo, and 2. that [we've already acknowledged the UI/UX limitations at this stage.](https://github.com/zooniverse/front-end-monorepo/pull/3446#issuecomment-1192407906)

> The interaction design here is very unforgiving of errors.
> If I start editing by mistake, how should I cancel? 'Esc' might work, but isn't available when drawing on a tablet with a stylus.

brb! Going to do a proper code read now and study how that "special case" interruption is actually happening.

2022-08-16 10:25 UTC, eatyourgreens commented
Here it is in Chrome 104 with slightly better event handling. I'll push these changes up.

https://user-images.githubusercontent.com/59547/184857368-4bb18f05-43c0-4aac-89aa-9bfdcfee7b51.mov

2022-08-18 20:21 UTC, shaunanoordin commented
Update acknowledged; I'm re-doing the code read, tests, and review now. 👍

2022-08-18 22:03 UTC, shaunanoordin approved these changes
## PR Review (Update)

Follows [previous review](https://github.com/zooniverse/front-end-monorepo/pull/3446#pullrequestreview-1073048576)

The latest update to this PR to fix the major issue where the Edit Freehand Line functionality wasn't working on Chrome.

- Fix here was to cancel the default event (see: `cancelEvent()` in `components/FreehandLine`)
  - Cancelling the default event stops the event from bubbling up to the Draggable wrapper, thus preventing the Draggable from running _pointer capture._

Code read looks good, and tests look good - there are no further blocking issues.

### Testing

Tested on localhost with macOS + Chrome with [a test project/workflow with Freehand Line drawing tool](https://local.zooniverse.org:8080/?env=staging&project=darkeshard%2Ftest-project-2022&workflow=3596)

Testing steps:
- Load the test workflow in lib-classifier, choose the Freehand Line tool
- Create a Freehand Line mark (drag & draw with a mouse)
  - Testing variations: (a) create a closed shape, (b) create an open shape, (c) select an existing FHL mark
- Once the FHL mark is selected, _double click_ anywhere on the _line_ to mark the "start of the segment to be edited/replaced" with a "start point"
- _Click_ anywhere on the lines to mark the "end of the segment" with an "end point"
- _Drag_ the start point to the end point, in a new path.
- Observe that the "segment to be edited/replaced" is now replaced with the new path

Note: the other issue, _"the correction feature acts very strangely if interrupted",_ still exists, but is not a blocker for this PR.

### Status

LGTM 👍 

This PR works as intended and meets the requirements to pass (i.e. the new functionality works and doesn't break anything that's already working). A follow up PR will be needed to address the _"the correction feature acts very strangely if interrupted"_ issue, but that's a tomorrow problem.

Let's get this merged!

2022-08-19 03:43 UTC, merged