Admin mode: Add admin flag to Zooniverse site header
zooniverse/front-end-monorepo pull request #3703
Opened 2022-09-27 11:36 UTC by eatyourgreens

- Refactor `ZooHeaderContainer` as a functional component, with hooks, in both NextJS apps.
- Add basic React Testing Library tests that check for the site navigation.
- add the `isAdmin` flag to `ZooHeader` on project pages.

## Package
app-content-pages
app-project

## How to Review
Project pages now have an 'Admin' link in the Zooniverse site menu when Admin Mode is enabled. Otherwise, The changes here shouldn't change how the site header works.

<img width="1246" alt="Screenshot of I Fancy Cats in Admin Mode, with an 'Admin' link in the main Zooniverse site navigation menu." src="https://user-images.githubusercontent.com/59547/192514582-07da0bbc-9bca-48fb-90b3-7042dda51232.png">

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## New Feature
- [ ] The PR creator has listed user actions to use when testing the new feature
- [ ] Unit tests are included for the new feature
- [ ] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

2022-10-04 13:01 UTC, eatyourgreens commented
After rewriting the `ZooHeader` tests with React Testing Library, then deleting all the Enzyme tests from sub-folders, the coverage looks pretty good.
<img width="376" alt="Coverage report for ZooHeader, from @zooniverse/react-components, showing 100% coverage for all sub-components." src="https://user-images.githubusercontent.com/59547/193825752-f95d18bd-250c-4833-a367-ce6254012ad1.png">

2022-10-16 16:01 UTC, goplayoutside3 commented
@mcbouslog I think I want to tag you in as a reviewer for this one because of your familiarity with notifications and sugar. I can't seem to figure out how to test unread notifications.

I ran app-project with this branch locally and visited a project page (PH TESS) while signed in to my account. I triggered 2 notifications on the production site by commenting on a Talk thread. I can see the 2 notifications in ZooHeader while viewing a PFE page such as All Projects on the production site. However, while viewing PH TESS on the locally run app-project, ZooHeader suddenly showed 6 notifications. Then I refreshed the local TESS page and now zero notifications show up.

The behavior I described seemed like a bug possibly on this branch, but then I realized that I when I'm signed in to my account on the production site, and visit an FEM project page such as TESS, I don't see any notifications there either. I can only see unread notifications in ZooHeader on a PFE page. Is it expected to never see unread notifications in FEM's ZooHeader?

2022-10-16 20:53 UTC, eatyourgreens commented
There are definitely bugs with unread notifications vanishing, see https://github.com/zooniverse/front-end-monorepo/issues/3672. I’m not sure if those are the same bug or two different bugs.

2022-10-20 04:13 UTC, mcbouslog requested changes
Generally looks great! One small change requested that would either apply to both apps or ZooHeader. 

I really like the consolidation of tests to main component and tests are very well written.

I tested starting from signed out, to singed in, enabling/disabling admin, navigating across project pages, signing out, and sign back in. All was as expected.

2022-10-20 04:13 UTC, mcbouslog commented on packages/app-content-pages/src/shared/components/ZooHeaderWrapper/ZooHeaderWrapperContainer.js
> +  const userProp = user.isLoggedIn ? { display_name, login } : {}
For the lib-react-components ZooHeader MainNavList `isAdmin={user?.admin && isAdmin}`, specifically `user?.admin` to be defined the following suggestion would be needed:

```suggestion
  const { admin, display_name, login } = user
  const userProp = user.isLoggedIn ? { admin, display_name, login } : {}
```

Or delete `user?.admin` from  lib-react-components ZooHeader MainNavList.

2022-10-20 04:17 UTC, mcbouslog commented
Regarding bug with Notifications and Messages, which is unrelated to these changes, I think `self.notifications.fetchAndSubscribe()` is missing from the [UserPersonalizaiton store `load` action](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/stores/User/UserPersonalization/UserPersonalization.js#L71-L74), I'll update a related issue or open a PR asap.

2022-10-20 04:47 UTC, eatyourgreens commented on packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js
> +      const user = { display_name: 'Zoo Admin', login: 'zoo-admin', admin: true }
Good catch.

2022-10-20 05:11 UTC, eatyourgreens commented on packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js
> +      const user = { display_name: 'Zoo Admin', login: 'zoo-admin', admin: true }
I’m puzzled now. How did I get the Admin link to show up in the screenshot at the top of this PR, if I wasn’t passing the `user.admin` flag from the API.

2022-10-20 05:24 UTC, mcbouslog commented on packages/lib-react-components/src/ZooHeader/ZooHeader.spec.js
> +      const user = { display_name: 'Zoo Admin', login: 'zoo-admin', admin: true }
Maybe early iteration when `user?.admin` was omitted or something else different? I was puzzled as well, I yarn bootstrapped and rebuilt lib-react-components more times than I care to admit 😆  convince I was missing/doing something wrong.

2022-10-20 05:25 UTC, mcbouslog approved these changes

2022-10-20 05:35 UTC, merged