Classifier: Refactor survey task tests
zooniverse/front-end-monorepo pull request #3933
Opened 2022-11-30 00:19 UTC by mcbouslog

## Package
- lib-classifier

## Describe your changes
- refactor survey task tests for when choice with required questions selected
- refactor some (not all, left at least one test with `getByRole` for related component) tests with `getByText` instead of `getByRole`

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
- What user actions should my reviewer step through to review this PR?
- Which storybook stories should be reviewed?
- Are there plans for follow up PR’s to further fix this bug or develop this feature?

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

2022-11-30 05:12 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +          const filterButton = getByText('SurveyTask.CharacteristicsFilter.filter')
Shouldn’t this be `screen.getByLabelText`?

2022-11-30 05:14 UTC, eatyourgreens reviewed
Is there a reason that you’re not using `screen` to run queries? 

Buttons and other labelled elements should use `getByLabelText` rather than `getByText`.

2022-11-30 05:18 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +          const filterButton = getByText('SurveyTask.CharacteristicsFilter.filter')
I think that applies to all the buttons in the tests.

2022-11-30 05:22 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
>            const cowHorseFilterButton = getByTestId('filter-LK-CWHRS')
This could use `screen.getByLabelText` too, since each icon should also have a text label.

2022-11-30 09:16 UTC, eatyourgreens commented
A couple of other thoughts:

- `within` can help to narrow the scope of a query. 
- you also have APIs like `querySelector` and `querySelectorAll` to find DOM nodes for testing. 
- you can use `beforeEach` to reduce repetition in test blocks.

2022-12-02 08:26 UTC, eatyourgreens requested changes
Don’t use ARIA labels to duplicate button labels.

2022-12-02 08:26 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.js
> +        a11yTitle={t('SurveyTask.CharacteristicsFilter.clearFilters')}
This button has a text label already. 
```suggestion
```

2022-12-02 08:26 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
> +          a11yTitle={`${t('SurveyTask.Choice.notThis')} ${choice.label}`}
Duplicated label. 
```suggestion
```

2022-12-02 08:26 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js
> +          a11yTitle={`${t('SurveyTask.Choice.identify')} ${choice.label}`}
Duplicated label. 
```suggestion
```

2022-12-02 15:55 UTC, eatyourgreens requested changes
Why has the Identify button label been changed to 'Identify Aardark', 'Identify Fire' etc? It should be 'Identify' for any choice.

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +        const choicesMenu = screen.getByTestId('choices-menu')
I think there's only one menu, so this can be:
```suggestion
        const choicesMenu = document.querySelector([role=menu])
```

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +          const stripesFilterButton = screen.getByTestId('filter-PTTRN-STRPS')
Maybe get these buttons by their label text, since they all have text labels.

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +          const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify Fire')
```suggestion
          const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify')
```
Why has the choice been added to the button label?

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +        const notThisButton = screen.getByLabelText('SurveyTask.Choice.notThis Nothing here')
```suggestion
        const notThisButton = screen.getByLabelText('SurveyTask.Choice.notThis')
```

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +        const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify Nothing here')
```suggestion
        const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify')
```

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +        let identifyButton = screen.getByLabelText('SurveyTask.Choice.identify Aardvark')
```suggestion
        let identifyButton = screen.getByLabelText('SurveyTask.Choice.identify')
```

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +        identifyButton = screen.getByLabelText('SurveyTask.Choice.identify Aardvark')
```suggestion
        identifyButton = screen.getByLabelText('SurveyTask.Choice.identify')
```

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +      const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify Fire')
```suggestion
      const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify')
```

2022-12-02 15:55 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +      const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify Fire')
```suggestion
      const identifyButton = screen.getByLabelText('SurveyTask.Choice.identify')
```

2022-12-02 15:56 UTC, eatyourgreens commented on packages/lib-classifier/src/plugins/tasks/survey/components/SurveyTask.spec.js
> +        const choicesMenu = screen.getByTestId('choices-menu')
`querySelector` might be faster. I'm not sure.

2022-12-02 18:26 UTC, mcbouslog commented
lib-react-components and Grommet buttons (Primary, Button, etc.) that define the label as a property on the component are not found with `getByLabelText`. If the noted buttons have an `a11yTitle` they are found with `getByLabelText`.

Components that are found with `getByLabelText`:
- [ChoiceButton](https://github.com/zooniverse/front-end-monorepo/blob/c8bc958cd755c91cfc62f50229c6415e7242b0e2/packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js#L58-L59)
- [FilterStatus](https://github.com/zooniverse/front-end-monorepo/blob/c8bc958cd755c91cfc62f50229c6415e7242b0e2/packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/FilterStatus/FilterStatus.js#L69-L70)

Components with defined labels that aren't found with `getByLabelText`:
- [ClearFilters](https://github.com/zooniverse/front-end-monorepo/blob/c8bc958cd755c91cfc62f50229c6415e7242b0e2/packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/CharacteristicsFilter/ClearFilters/ClearFilters.js#L29-L34)
- (within [Choice](https://github.com/zooniverse/front-end-monorepo/blob/c8bc958cd755c91cfc62f50229c6415e7242b0e2/packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js#L95-L105)) Not this
- (within [Choice](https://github.com/zooniverse/front-end-monorepo/blob/c8bc958cd755c91cfc62f50229c6415e7242b0e2/packages/lib-classifier/src/plugins/tasks/survey/components/components/Choice/Choice.js#L95-L105)) Identify

2022-12-02 18:38 UTC, eatyourgreens commented
Is that because you're looking for eg. `SurveyTask.Choice.identify` but the label is 'Identify'?

2022-12-02 18:48 UTC, eatyourgreens commented
No wait, the docs says this:
>The example above does NOT find the input node for label text broken up by elements. 
https://testing-library.com/docs/queries/bylabeltext#name

So those buttons could be failing because they use HTML markup in their labels. [ChoiceButton](https://github.com/zooniverse/front-end-monorepo/blob/c8bc958cd755c91cfc62f50229c6415e7242b0e2/packages/lib-classifier/src/plugins/tasks/survey/components/components/Chooser/components/Choices/components/ChoiceButton.js#L58-L59) here, for example, has markup in its label, because it uses images.

`ChoiceButton` there, by the way, should not have an ARIA label. A button should either have a text label:
```html
<button>Text label</button>
```
or an ARIA label: 
```html
<button aria-label="Text label"><img /></button>
```
but never both together.

To be honest, in that second case the button label should be image alt text.
```html
<button><img alt="Text label" /></button>
```

2022-12-02 22:50 UTC, mcbouslog commented
For buttons with HTML markup in the labels, preventing use of `getByLabelText`, what do you think is the preferred query? I think ideally it'd be 'getByRole('button', { name: 'Aardvark' })`, but that query takes awhile, so maybe for these tests `getByText`?

2022-12-03 10:28 UTC, eatyourgreens commented
This query will find all menu item checkboxes inside the first menu on the page. 

```js
querySelector([role=“menu”]).querySelectorAll([role=“menuitem”])
```

If the checkboxes have values, you can further refine the query with `[value=“Aardvark”]`. Otherwise, you could pluck the first item from the returned `NodeList`, or filter the node list by inspecting the text of each element to find a particular button. 

Stepping back from specific tests, is the run time being spent rendering the survey task, or running queries? If it’s rendering excessively, you can cache rendered nodes in variables and reuse them. Have a look at the `Classifier` tests, which do this because they are also slow. The `Classifier` tests are also split into two files, so consider that too.

2022-12-03 10:50 UTC, eatyourgreens approved these changes

2022-12-03 11:06 UTC, eatyourgreens commented
Reading the source code, label text queries ignore buttons.
https://github.com/testing-library/dom-testing-library/blob/edffb7c5ec2e4afd7f6bedf842c669ddbfb73297/src/queries/label-text.ts#L25

2022-12-03 17:59 UTC, eatyourgreens commented
Also noting here that `ChoiceButton`, linked above, wraps a `div` with `button`, which is invalid HTML.

2022-12-06 11:21 UTC, eatyourgreens commented
This is running a lot faster now on my laptop, though the excessive rendering is still making it quite slow.

I've rebased and added a commit that renders a story once, in a `before()` block, then tests the output DOM of that story in separate `it()` blocks. You can use that as an example to speed up the other test blocks. There are a lot of tests where you run the same render multiple times. You could run it once, store the output in variables then test each of those variables in `it()` blocks.

I also fixed a bug in the 'Clear FIlters' button, which had the wrong label. text Your tests had caught the bug, but you'd updated the tests to pass by using the broken label, rather than fixing the button so that it passed with the expected label.

2022-12-06 11:28 UTC, eatyourgreens commented
CI isn't timing out, so I'm happy for this to be merged as-is.

2022-12-06 17:31 UTC, eatyourgreens commented
>The filters can be removed by tabbing to the close/remove button within the filter and pressing space or enter. 

This is a bug. See #3919. Tab on each radio button should take you out of the radio button group and on to the next focusable element on the page.

2022-12-06 17:35 UTC, eatyourgreens commented
FWIW, I'm toggling the selected radio button with the cursor keys, then trying Space or Enter to clear the selected value.

2022-12-06 17:44 UTC, merged