Set classification userLanguage from locale
zooniverse/front-end-monorepo pull request #4868
Opened 2023-06-21 14:44 UTC by eatyourgreens

Add an `_onLocaleChange` listener to `ClassificationMetadata`, which sets `metadata.userLanguage` from the root store locale.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-classifier

## Linked Issue and/or Talk Post
- closes #4521.

## How to Review
If you change language during a classification, the classification metadata should update to match the current language.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

2023-06-21 20:34 UTC, goplayoutside3 requested changes
Run locally, I went to [Planet Hunters TESS](https://localhost.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess/classify) Classify page. I changed the locale from English to Spanish via the locale dropdown. I made a classification, but the user language still displays as "en":
<img width="262" alt="Screenshot 2023-06-21 at 3 30 41 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/6e0cc9cb-a35f-4590-8b4f-ca40a73d437c">

The next classification I make accurately reflects a locale change, but the first after using the locale dropdown does not.

2023-06-21 20:55 UTC, eatyourgreens commented
I wonder if the classifier store locale is being updated properly when the menu selection changes. 🤔

2023-06-22 07:02 UTC, eatyourgreens commented
Hmmmm. 🤔 

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[_onLocaleChange]' ReferenceError: getRoot is not defined
```

2023-06-22 07:10 UTC, eatyourgreens commented
@goplayoutside3 should be working now. Weird that that error didn't come up when you were reviewing the code, but it was an easy fix.

2023-06-22 19:25 UTC, goplayoutside3 approved these changes
Looks good!

2023-06-22 19:41 UTC, merged