CloseButton: Remove enzyme and convert to RTL
zooniverse/front-end-monorepo pull request #5254
Opened 2023-08-29 21:25 UTC by kieftrav

## Package
lib-react-components

## Describe your changes
Converted tests for the CloseButton from Enzyme to RTL. 

## How to Review
[CloseButton Story](http://localhost:9001/?path=/story/components-closebutton--default)

## General
- [ ] Unit Tests are passing locally and on Github
- [ ] Storybook renders as expected
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

2023-09-18 14:18 UTC, shaunanoordin requested changes
## PR Review

Package: `lib-react-components`

This PR makes updates to the CloseButton component's tests and Storybook story.

Code changes _mostly_ look good - the tests are testing basic rendering, and the storybook shows relevant use cases - but there's a small problem with how getByRole() is used.

### Status

Changes requested:
- [ ] [] remove `{ disabled: ... }` argument in `screen.getByRole('button', { disabled: false })`
  - Reason: "disabled" [isn't a valid option for getByRole](https://testing-library.com/docs/queries/byrole), and gives people reading the test a false assurance.
- [ ] [optional]: instead of trying to select a disabled/not-disabled button, use hasAttribute, e.g. `expect(myExampleButton.hasAttribute('disabled')).to.be.false()`, to determine if a button is disabled/not-disabled.

Other than that small thing, everything else looks good. 👌

2023-09-18 14:18 UTC, shaunanoordin commented on packages/lib-react-components/src/CloseButton/CloseButton.spec.js
> +    expect(screen.getByRole('button', { disabled: false })).to.be.ok()
⚠️ Ahhah, we've got a small problem here - `disabled: false/true` isn't actually a proper option for getRole()

Check out the `options?` listed in [RTL's ByRole documentation](https://testing-library.com/docs/queries/byrole) -
there's `hidden`, `name`, `description`, etc, but you can't select by disabled state.

You can test this yourself by changing `disabled: false` to `disabled: true`, and the `expect()` will _still_ say, yep, that's definitely `ok()`. This means that getByRole() is ignoring the invalid "disabled" option.

2023-09-18 14:18 UTC, shaunanoordin commented on packages/lib-react-components/src/CloseButton/CloseButton.spec.js
> +    expect(screen.getByRole('button', { disabled: false })).to.be.ok()
One option is to do check the `disabled` attribute separately.

For example, we can replace...
```
expect(screen.getByRole('button', { disabled: false })).to.be.ok()
```

With...
```
const button = screen.getByRole('button')
expect(button).to.be.ok()
expect(button.hasAttribute('disabled')).to.be.false()
```

2023-09-18 14:18 UTC, shaunanoordin commented on packages/lib-react-components/src/CloseButton/CloseButton.spec.js
> +    expect(screen.getByRole('button', { disabled: true })).to.be.ok()
Same comment as above: `disabled` is not a valid option for `getByRole()`

2023-09-18 14:18 UTC, shaunanoordin commented on packages/lib-react-components/src/CloseButton/CloseButton.spec.js
> +    expect(screen.getByRole('button', { disabled: false })).to.be.ok()
Same comment as above: `disabled` is not a valid option for `getByRole()`

2024-01-17 14:29 UTC, kieftrav commented on packages/lib-react-components/src/CloseButton/CloseButton.spec.js
> +describe('Component > CloseButton', function () {
I'm not sure if there's any actual standard naming here. Probably something to talk about at some point

2024-02-29 16:50 UTC, shaunanoordin approved these changes
## PR Review (Update)

I'm sorry I've been sitting on this one's re-review for so long! I wasn't paying attention to the updates, and didn't realise that the feedback about changing `getByRole()`'s use of `disabled` has already been addressed. 👍 

LGTM, let's get this PR merged!

2024-03-02 17:33 UTC, merged