ZRC: Refactor ZooHeader to avoid hydration errors
zooniverse/front-end-monorepo pull request #5278
Opened 2023-09-04 13:59 UTC by eatyourgreens

- wrap both `SignedInUserNavigation` and `SignedOutUserNavigation` in a labelled `nav` element, to avoid this hydration error in the header: `Expected server HTML to contain a matching <nav> in <div>.` (#5273)
- bump `@zooniverse/react-components` to 1.5.6.
- update the changelog.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
 - lib-react-components
 
## Linked Issue and/or Talk Post
- towards #5273.

## How to Review
Run the project app with `yarn dev`. Some page components will still throw mismatch errors, but they should be fixed in `ZooHeader`. Sign in and out should continue to work as before.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

2023-09-12 17:06 UTC, kieftrav commented on packages/lib-react-components/src/ZooHeader/ZooHeader.js
> +        {Object.keys(user).length === 0 ?
Clever use of detecting an empty object!

2023-09-12 17:07 UTC, kieftrav commented on packages/lib-react-components/src/ZooHeader/components/SignedOutUserNavigation/SignedOutUserNavigation.js
> +        <NavButton label={t('ZooHeader.SignedOutUserNavigation.signIn')} onClick={signIn} />
I appreciate the cleanup here!

2023-09-12 17:18 UTC, eatyourgreens commented on packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js
>  // TODO: This component is causing a styled-components error and needs a fix
Sure. I’m not really sure what bug this comment is referring to. I think we can get rid of it.

2023-09-12 17:20 UTC, kieftrav commented
@eatyourgreens - I'm getting hydration errors when I visit a page that returns a 404. Attached are two screenshots - one of which is when I'm signed in locally and the other when I'm signed out.

My testing process was to:
1) pulled down the PR
2) perform a `yarn panic && yarn boostrap` for a fresh build
3) ran `yarn dev` in my local `packages/app-project` directory
4) After loading a 404 testing page (https://local.zooniverse.org:3000/projects/test404) I was able to generate the below, attached screenshots.

Let me know if there's anything else you want me to try from a config/env standpoint. 

<img width="2028" alt="Screenshot 2023-09-12 at 12 15 27 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/733986/b4a8b463-25b9-491a-8b39-4fd9dedfe1b6">
<img width="2053" alt="Screenshot 2023-09-12 at 12 15 41 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/733986/092fa2da-ae73-493a-91a0-ea94da52d716">
![Screenshot 2023-09-12 at 12 19 03 PM](https://github.com/zooniverse/front-end-monorepo/assets/733986/3b48c136-97d2-4f40-82f2-f071801b7dde)

2023-09-12 17:22 UTC, kieftrav requested changes
Looks like I'm still getting hydration issues on a 404 page. See comment on main conversation thread.

2023-09-12 17:24 UTC, eatyourgreens commented
Yeah, our pages are full of hydration errors. This PR tries to address one specific error, where the `nav` element is present in the client-side render but not in the initial server render. 

I'm not sure what to advise, because it's not immediately obvious from the stack trace which component is erroring or which element is mismatched.

2023-09-12 17:26 UTC, eatyourgreens commented
Your screenshots are catching mismatched links. I'm pretty sure that happens because the logged-out menu (SSR) renders buttons, but the logged-in menu (browser) renders links. ☹️

2023-09-13 13:37 UTC, kieftrav approved these changes
After chatting about hydration errors with Jim we concluded my hydration error is due to user sign in state not being known during server side rendering. Because I cannot recreate the bug and there's no short term fix for hydration issues related to logged in user state this LGTM.

2023-09-13 13:40 UTC, eatyourgreens commented
I think the overall approach here is to find these errors and fix them one-by-one, in components that depend on logged-in user state.

2023-09-13 13:46 UTC, eatyourgreens commented on packages/lib-react-components/src/ZooHeader/components/NavListItem/NavListItem.js
>  // TODO: This component is causing a styled-components error and needs a fix
```suggestion
```

2023-09-13 13:57 UTC, merged