Fix missing padding in the logged-out user menu
zooniverse/front-end-monorepo pull request #5327
Opened 2023-09-13 14:46 UTC by eatyourgreens

PR #5278 accidentally removed the padding from the signed-out user navigation menu in `ZooHeader`. This restores it.

## Package
- lib-react-components

## How to Review
Compare the signed-out user navigation menu with the live web site.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

2023-09-13 19:57 UTC, goplayoutside3 requested changes
Please run this branch locally and double check. On loading it in Chrome, the padding of the header is way too large: 
<img width="1352" alt="Screenshot 2023-09-13 at 2 57 22 PM" src="https://github.com/zooniverse/front-end-monorepo/assets/23665803/180c3e18-08b2-46f4-9f38-a0aea8871624">

2023-09-13 20:56 UTC, eatyourgreens commented
Oh, that’s not good. I did check it locally before opening the PR, both logged in and logged out.

2023-09-14 08:22 UTC, eatyourgreens commented
Here's the top bar in Firefox:
<img width="600" alt="Screenshot of the Zooniverse site navigation in Firefox, with normal padding." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/353033ba-bbf9-46bf-bba0-77ac8e9f8e0d">

And Chrome:
<img width="600" alt="Screenshot of the Zooniverse site navigation in Firefox, with padding that's double what it should be." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/cc2b1e17-8646-4df7-990d-975803273b7e">

I'll take a look to see why the padding is double what it should be in Chrome. I don't see anything obvious in the changes here that would do that. The only difference I see in the HTML is that the signed-out menu uses buttons, but the signed-in menu uses links.

2023-09-14 08:49 UTC, eatyourgreens commented
My fix is to apply padding only when you're logged out but it seems odd that the height of that box changes depending on whether it contains links or buttons.

2023-09-14 10:18 UTC, eatyourgreens commented
I figured it out: the user account dropdown menu button has internal padding which sets the height of the whole top bar. Note that `div` inside `button` here is invalid HTML, so that may cause problems too.

<img width="600" alt="Zooniverse site navigation, with a signed-in user and the user account button highlighted in the DOM inspector, showing the padding around the button label." src="https://github.com/zooniverse/front-end-monorepo/assets/59547/8faae752-26c3-49de-a341-4c8101fd54e5">

2023-09-14 11:02 UTC, eatyourgreens commented
I've fixed the invalid HTML for the button label, replacing the `div` with `span`. I left the padding on the button itself. I wasn't sure if we want to have the padding inside or outside the clickable area. It's currently inside the clickable area, so I've left that alone.

2023-09-14 15:53 UTC, mcbouslog approved these changes
Confirmed styling looks good on Chrome, Safari, and Firefox 👍

2023-09-14 16:04 UTC, merged